classes = [
  {
    id: "1",
    title: " ",
    category: "tap",
    subCategory: "",
    startTime: 660,
    weekDays: [1, 3],
    duration: 60,
    level: 10,
    teacher: ["rof"],
  },
  {
    id: "2",
    title: " ",
    category: "tap",
    subCategory: "",
    startTime: 1110,
    weekDays: [1, 3],
    duration: 60,
    level: 10,
    teacher: ["lam"],
  },
  {
    id: "3",
    title: " ",
    category: "tap",
    subCategory: "",
    startTime: 1260,
    weekDays: [4],
    duration: 75,
    level: 10,
    teacher: ["fru"],
  },
  {
    id: "4",
    title: " ",
    category: "tap",
    subCategory: "",
    startTime: 570,
    weekDays: [5],
    duration: 90,
    level: 10,
    teacher: ["rof"],
  },
  {
    id: "5",
    title: " ",
    category: "tap",
    subCategory: "",
    startTime: 885,
    weekDays: [5],
    duration: 90,
    level: 10,
    teacher: ["rof"],
  },
  {
    id: "6",
    title: " ",
    category: "tap",
    subCategory: "",
    startTime: 600,
    weekDays: [6],
    duration: 60,
    level: 10,
    teacher: ["mn"],
  },
  {
    id: "7",
    title: "",
    category: "tap",
    subCategory: "",
    startTime: 960,
    weekDays: [1],
    duration: 90,
    level: 20,
    teacher: ["il"],
  },
  {
    id: "8",
    title: "",
    category: "tap",
    subCategory: "",
    startTime: 960,
    weekDays: [3],
    duration: 90,
    level: 20,
    teacher: ["il"],
  },
  {
    id: "9",
    title: "",
    category: "tap",
    subCategory: "",
    startTime: 1260,
    weekDays: [1],
    duration: 75,
    level: 20,
    teacher: ["dc"],
  },
  {
    id: "10",
    title: "",
    category: "tap",
    subCategory: "",
    startTime: 570,
    weekDays: [2, 4],
    duration: 75,
    level: 20,
    teacher: ["rof"],
  },
  {
    id: "11",
    title: "",
    category: "tap",
    subCategory: "",
    startTime: 1215,
    weekDays: [3],
    duration: 75,
    level: 20,
    teacher: ["mb"],
  },
  {
    id: "12",
    title: "  avançats",
    category: "tap",
    subCategory: "",
    startTime: 9,
    weekDays: [5],
    duration: 90,
    level: 20,
    teacher: ["ap"],
  },
  {
    id: "13",
    title: "  avançats",
    category: "tap",
    subCategory: "",
    startTime: 870,
    weekDays: [5],
    duration: 90,
    level: 20,
    teacher: ["il"],
  },
  {
    id: "14",
    title: "  avançats",
    category: "tap",
    subCategory: "",
    startTime: 660,
    weekDays: [6],
    duration: 90,
    level: 20,
    teacher: ["mn"],
  },
  {
    id: "15",
    title: " Mig",
    category: "tap",
    subCategory: "",
    startTime: 570,
    weekDays: [1, 3],
    duration: 75,
    level: 30,
    teacher: ["fru"],
  },
  {
    id: "16",
    isTapProgram: true,
    title: " Mig",
    category: "tap",
    subCategory: "",
    startTime: 960,
    weekDays: [1, 3],
    duration: 90,
    level: 30,
    teacher: ["fru", "fru", "mb"],
  },
  {
    id: "17",
    title: " Mig",
    category: "tap",
    subCategory: "",
    startTime: 1140,
    weekDays: [1, 3],
    duration: 75,
    level: 30,
    teacher: ["mb"],
  },
  {
    id: "18",
    title: " Mig",
    category: "tap",
    subCategory: "",
    startTime: 885,
    weekDays: [2, 4],
    duration: 75,
    level: 30,
    teacher: ["dg", "rof", "rof"],
  },
  {
    id: "19",
    isTapProgram: true,
    title: " Mig",
    category: "tap",
    subCategory: "",
    startTime: 960,
    weekDays: [2, 4],
    duration: 90,
    level: 30,
    teacher: ["ep", "ga", "ga"],
  },
  {
    id: "20",
    title: " Mig",
    category: "tap",
    subCategory: "",
    startTime: 1245,
    weekDays: [2, 4],
    duration: 75,
    level: 30,
    teacher: ["mn"],
  },
  {
    id: "21",
    title: " Mig",
    category: "tap",
    subCategory: "",
    startTime: 555,
    weekDays: [3],
    duration: 90,
    level: 30,
    teacher: ["mb"],
  },
  {
    id: "22",
    title: " Mig",
    category: "tap",
    subCategory: "",
    startTime: 960,
    weekDays: [3],
    duration: 90,
    level: 30,
    teacher: ["il"],
  },
  {
    id: "23",
    isTapProgram: true,
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 570,
    weekDays: [1, 3],
    duration: 75,
    level: 40,
    teacher: ["rof", "rof", "ep"],
  },
  {
    id: "24",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 645,
    weekDays: [1, 3],
    duration: 75,
    level: 40,
    teacher: ["lam"],
  },
  {
    id: "25",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 1020,
    weekDays: [1, 3],
    duration: 90,
    level: 40,
    teacher: ["lam"],
  },
  {
    id: "26",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 1170,
    weekDays: [1, 3],
    duration: 90,
    level: 40,
    teacher: "sl",
  },
  {
    id: "27",
    isTapProgram: true,

    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 570,
    weekDays: [2, 4],
    duration: 75,
    level: 40,
    teacher: ["rs", "mb", "fru"],
  },
  {
    id: "28",
    isTapProgram: true,

    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 645,
    weekDays: [2, 4],
    duration: 75,
    level: 40,
    teacher: ["dg", "ga", "ga"],
  },
  {
    id: "29",
    startsAt: datetime(2023, 9, 20).strftime("%Y-%m-%d"),
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 1230,
    weekDays: [2],
    duration: 90,
    level: 40,
    teacher: ["ep"],
  },
  {
    id: "22",
    title: " Mig",
    category: "tap",
    subCategory: "",
    startTime: 960,
    weekDays: [3],
    duration: 90,
    level: 30,
    teacher: ["il"],
  },
  {
    id: "23",
    isTapProgram: true,
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 570,
    weekDays: [1, 3],
    duration: 75,
    level: 40,
    teacher: ["rof", "rof", "ep"],
  },
  {
    id: "24",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 645,
    weekDays: [1, 3],
    duration: 75,
    level: 40,
    teacher: ["lam"],
  },
  {
    id: "25",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 1020,
    weekDays: [1, 3],
    duration: 90,
    level: 40,
    teacher: ["lam"],
  },
  {
    id: "26",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 1170,
    weekDays: [1, 3],
    duration: 90,
    level: 40,
    teacher: "sl",
  },
  {
    id: "27",
    isTapProgram: true,

    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 570,
    weekDays: [2, 4],
    duration: 75,
    level: 40,
    teacher: ["rs", "mb", "fru"],
  },
  {
    id: "28",
    isTapProgram: true,

    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 645,
    weekDays: [2, 4],
    duration: 75,
    level: 40,
    teacher: ["dg", "ga", "ga"],
  },
  {
    id: "29",
    startsAt: datetime(2023, 9, 20).strftime("%Y-%m-%d"),
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 1230,
    weekDays: [2],
    duration: 90,
    level: 40,
    teacher: ["ep"],
  },
  {
    id: "30",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 570,
    weekDays: [1, 3],
    duration: 75,
    level: 40,
    teacher: ["rof", "rof", "ep"],
  },
  {
    id: "31",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 645,
    weekDays: [1, 3],
    duration: 75,
    level: 40,
    teacher: ["lam"],
  },
  {
    id: "32",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 1020,
    weekDays: [1, 3],
    duration: 90,
    level: 40,
    teacher: ["lam"],
  },
  {
    id: "33",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 1170,
    weekDays: [1, 3],
    duration: 90,
    level: 40,
    teacher: "sl",
  },
  {
    id: "34",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 570,
    weekDays: [2, 4],
    duration: 75,
    level: 40,
    teacher: ["rs", "mb", "fru"],
  },
  {
    id: "35",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 645,
    weekDays: [2, 4],
    duration: 75,
    level: 40,
    teacher: ["dg", "ga", "ga"],
  },
  {
    id: "36",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 1230,
    weekDays: [2],
    duration: 90,
    level: 40,
    teacher: ["ep"],
  },
  {
    id: "37",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 930,
    weekDays: [5],
    duration: 120,
    level: 40,
    teacher: ["ep"],
  },
  {
    id: "38",
    title: " Mig/avançat",
    category: "tap",
    subCategory: "",
    startTime: 765,
    weekDays: [6],
    duration: 90,
    level: 40,
    teacher: ["mn"],
  },
  {
    id: "39",
    title: " Avançat",
    category: "tap",
    subCategory: "",
    startTime: 720,
    weekDays: [1, 3],
    duration: 75,
    level: 50,
    teacher: ["mb", "lam", "lam"],
  },
  {
    id: "40",
    title: " Avançat",
    category: "tap",
    subCategory: "",
    startTime: datetime(2021, 10,1) .strftime("%Y-%m-%d"),
    weekDays: [1, 3],
    duration: 75,
    level: 50,
    teacher: ["ga"],
  },
  {
    id: "41",
    title: " Avançat",
    category: "tap",
    subCategory: "",
    startTime: 900,
    weekDays: [1],
    duration: 120,
    level: 50,
    teacher: ["ep"],
  },
  {
    id: "42",
    title: " Avançat",
    category: "tap",
    subCategory: "",
    startTime: 1080,
    weekDays: [1, 3],
    duration: 90,
    level: 50,
    teacher: "sl",
  },
  {
    id: "43",
    title: " Avançat",
    category: "tap",
    subCategory: "",
    startTime: 720,
    weekDays: [2, 4],
    duration: 75,
    level: 50,
    teacher: ["dg", "rof", "rof"],
  },
  {
    id: "44",
    title: " Avançat",
    category: "tap",
    subCategory: "",
    startTime: 795,
    weekDays: [2, 4],
    duration: 75,
    level: 50,
    teacher: ["ep", "ep", "fru"],
  },
  {
    id: "45",
    title: " Avançat",
    category: "tap",
    subCategory: "",
    startTime: 900,
    weekDays: [3],
    duration: 120,
    level: 50,
    teacher: ["dg", "ep", "ep"],
  },
  {
    id: "46",
    title: " Avançat",
    category: "tap",
    startTime: 2030,
    weekDays: [3],
    duration: 90,
    level: 50,
    teacher: ["cm"],
  },
  {
    id: "47",
    title: "Improvisació",
    category: "tap",
    subCategory: "tapImprov",
    startTime: 1140,
    weekDays: [3],
    duration: 90,
    startsAt: datetime(2023, 10, 1).strftime("%Y-%m-%d"),
    teacher: ["cm"],
  },
  {
    id: "48",
    title: "Cajón i ",
    category: "tap",
    subCategory: "tapCajon",
    startTime: 960,
    weekDays: [5],
    duration: 90,
    teacher: ["te"],
  },
  {
    id: "49",
    title: "Cant per a ballarins de ",
    category: "tap",
    subCategory: "tapMusic",
    startTime: 630,
    weekDays: [2],
    duration: 75,
    teacher: ["ef"],
  },
  {
    id: "50",
    title: "Cant per a ballarins de ",
    category: "tap",
    subCategory: "tapSinging",
    startTime: 735,
    weekDays: [2],
    duration: 75,
    teacher: ["ef"],
  },
  {
    id: "51",
    title: "Música per a ballarins de ",
    category: "tap",
    subCategory: "tapMusic",
    startTime: 615,
    weekDays: [4],
    duration: 90,
    teacher: ["ts"],
  },
  {
    id: "52",
    title: "Música per a ballarins de ",
    category: "tap",
    subCategory: "tapMusic",
    startTime: 735,
    weekDays: [4],
    duration: 90,
    teacher: ["ts"],
  },
  {
    id: "53",
    title: "Infants principiants",
    category: "tap",
    subCategory: "",
    startTime: 1750,
    weekDays: [5],
    level: 10,
    duration: 90,
    teacher: ["il"],
  },
  {
    id: "54",
    title: "Infants Pr. Av.",
    category: "tap",
    subCategory: "tapKids",
    startTime: 1050,
    weekDays: [1],
    level: 20,
    duration: 60,
    teacher: ["il"],
  },
  {
    id: "55",
    title: "Joves Pr. Av.",
    category: "tap",
    subCategory: "tapkids",
    startTime: 1110,
    weekDays: [1],
    level: 20,
    duration: 90,
    teacher: ["il"],
  },
  {
    id: "56",
    title: "Joves Mig",
    category: "tap",
    subCategory: "tapkids",
    startTime: 1050,
    weekDays: [3],
    level: 30,
    duration: 90,
    startsAt: datetime(2023, 9, 13).strftime("%Y-%m-%d"),
    teacher: ["il"],
  },
  {
    id: "57",
    title: "Companyia Jove",
    category: "tap",
    subCategory: "tapCompany",
    startTime: 1200,
    weekDays: [1],
    duration: 120,
    teacher: [],
  },
];